name: walletconnect_modal_flutter
description: The WalletConnectModal for WalletConnect built using Flutter.
version: 2.1.14
repository: https://github.com/WalletConnect/WalletConnectModalFlutter

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  walletconnect_flutter_v2: ^2.1.14
  flutter_svg: ^2.0.9
  qr_flutter: ^4.1.0
  json_annotation: ^4.8.1
  url_launcher: ^6.2.4
  universal_io: ^2.2.2
  w_common: ^3.0.1
  logger: ^2.0.2+1
  http: ^1.2.0
  freezed_annotation: ^2.4.1
  smooth_page_indicator: ^1.1.0
  event: ^2.1.2
  flutter_keyboard_visibility: ^6.0.0
  appcheck: ^1.0.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_version: ^2.1.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  freezed: ^2.4.6
  mockito: ^5.4.4
  network_image_mock: ^2.1.1
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/help_page/
    - assets/icons/

